name: SS

on:
  push:
    branches:
      - 'uat'
jobs:
  commitfromuat:
    name: push to ss-gitops
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: echoing
        run: | 
                echo "hello"
      - name: gitstatus
        run: |
                git status
