name: SS

on:
  push:
    branches:
      - 'main'

jobs:
  commit:
    name: push to uat
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: gitting
        run: | 
                number='0'
                number2=50
                
      - name: echoing
        run: |  
                number=50
                echo "number=$number" >> $GITHUB_ENV
                
                
            
      - name: gitting   
        run: |
               git clone https://github.com/Vaishnavi20011225/ss-gitops.git
               git config --global user.email "vaishnavi.korgaonkar@wohlig.com"
               git config --global user.name "Vaishnavi20011225"

               cd ss-gitops
               ls
               echo ${{ env.number }}
              
               
               cat gitops.txt
               sed -i -e 's/$number/50/g' gitops.txt
               cat gitops.txt
               NUMBER=$(echo gitops.txt | sed 's/[^0-9]*//g') ; echo $NUMBER
               
              
    
               

               

                
              
      
