name: SS

on:
  push:
    branches:
      - 'main'

jobs:
  commit:
    name: push to uat
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: echoing
        run: |
                echo "uat"
        
      
