name: SS

on:
  push:
    branches:
      - 'main'

jobs:
  commit:
    name: push to uat
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: gitting
        run: |
               git clone https://github.com/Vaishnavi20011225/ss-gitops.git
               git config --global user.email "vaishnavi.korgaonkar@wohlig.com"
               git config --global user.name "Vaishnavi20011225"

               cd ss-gitops
               ls
               cat gitops.txt

                
              
      
